# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8063d897626aa41c381485e3fbaa2cbeeb82ae9a9b1d2088460a208c41632c41a70064d3b93302fa98e15053a0a19b83fa92e4bc096e5bf38119cdf6ebd7497c

test:
  secret_key_base: 4f833e0e184888c94944578380b4ac25a875f8de5e8e02380c00d34ba8e646c0fc72aa61a203cbf5c6c1da556c3364c1a6f9e90ed042d53ef3a671524376993a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
